version: "3"
services:
    elasticsearch:
        image: "elasticsearch:7.9.3"
        container_name: "elasticsearch"
        ports: 
            - "9200:9200"
        environment: 
            - discovery.type=single-node
        volumes: 
            - data:/usr/share/elasticsearch/data

volumes:
    data: